Add pipeline cleanup steps

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,6 +21,16 @@ jobs:
           gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
           echo "GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
           echo "y" | gcloud auth configure-docker
+
+      # ----- CLEANUP DOCKER CONTAINERS -----
+      - name: Cleanup Before Deployments
+        run: |
+          ssh -o StrictHostKeyChecking=no cole_hodler@35.242.176.107 '
+            docker stop $(docker ps -a -q) || true;
+            docker rm $(docker ps -a -q) || true;
+            docker system prune -af --volumes;
+            df -h;
+          '
           
       # ----- FRONTEND -----
       - name: Build React App Docker Image
@@ -37,8 +47,9 @@ jobs:
           ssh -o StrictHostKeyChecking=no cole_hodler@35.242.176.107 '
             docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest &&
             docker ps -a | grep -q react-app && docker stop react-app && docker rm react-app;
-            docker run -d --name react-app -p 3000:80 gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
+            docker run -d --name react-app --restart unless-stopped -p 3000:80 gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
           '          
+
       # ----- BACKEND -----
       - name: Build Spring Boot App Docker Image
         working-directory: backend
@@ -75,5 +86,5 @@ jobs:
           ssh -o StrictHostKeyChecking=no cole_hodler@35.242.176.107 '
             docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-microservice:latest &&
             docker ps -a | grep -q python-app && docker stop python-app && docker rm python-app;
-            docker run -d --name python-app -p 5000:5000 --restart unless-stopped gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-microservice:latest
+            docker run -d --name python-app --restart unless-stopped -p 5000:5000 gcr.io/${{ secrets.GCP_PROJECT_ID }}/python-microservice:latest
           '
